import 'server-only'

import { API_BASE_URL, hasBackend } from '@/lib/env'
import { getAccessToken } from '@/lib/supabase/server'

/**
 * The frontend's only route to AI.
 *
 * Every generation call goes to the FastAPI backend, which owns the single
 * Anthropic client (`api/app/services/ai.py`). The API key never reaches this
 * process, let alone the browser.
 *
 * When no backend is configured, each function degrades to a deterministic
 * local composer so the free tools and in-app generate buttons still produce
 * something usable. Responses carry `source` so the UI can say which happened
 * rather than passing a template off as a model call.
 */

export type GenerationSource = 'claude' | 'offline'

export interface Generated<T> {
  data: T
  source: GenerationSource
  note?: string
}

const OFFLINE_NOTE =
  'Generated by the built-in composer. Connect the backend with an ANTHROPIC_API_KEY for model-written output.'

async function callBackend<T>(path: string, payload: unknown, timeoutMs = 45_000): Promise<T | null> {
  if (!hasBackend) return null

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)

  try {
    const token = await getAccessToken()
    const response = await fetch(`${API_BASE_URL}${path}`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        ...(token ? { authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify(payload),
      signal: controller.signal,
      cache: 'no-store',
    })
    if (!response.ok) return null
    return (await response.json()) as T
  } catch {
    return null
  } finally {
    clearTimeout(timer)
  }
}

/* ============================================ Website analysis */

export interface WebsiteAnalysis {
  what_you_sell: string
  who_you_target: string
  how_to_pitch: string
}

const stripTags = (html: string) =>
  html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()

function firstMatch(html: string, pattern: RegExp): string | null {
  const match = html.match(pattern)
  return match?.[1]?.trim() || null
}

/** Heuristic fallback: read the page ourselves and compose from real content. */
async function analyzeOffline(url: string): Promise<WebsiteAnalysis> {
  let title: string | null = null
  let description: string | null = null
  let heading: string | null = null
  let body = ''

  try {
    const response = await fetch(url, {
      headers: { 'user-agent': 'OutreachHalo/1.0 (+https://outreachhalo.com)' },
      signal: AbortSignal.timeout(12_000),
    })
    if (response.ok) {
      const html = await response.text()
      title = firstMatch(html, /<title[^>]*>([^<]+)<\/title>/i)
      description =
        firstMatch(html, /<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)["']/i) ??
        firstMatch(html, /<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']+)["']/i)
      heading = firstMatch(html, /<h1[^>]*>([\s\S]*?)<\/h1>/i)
      if (heading) heading = stripTags(heading)
      body = stripTags(html).slice(0, 600)
    }
  } catch {
    // Unreachable site — fall through to the hostname-only version below.
  }

  const host = (() => {
    try {
      return new URL(url).hostname.replace(/^www\./, '')
    } catch {
      return url
    }
  })()

  const brand = (title ?? host).split(/[|\-–—]/)[0].trim() || host

  return {
    what_you_sell:
      description ??
      heading ??
      (body ? `${body.slice(0, 180).trim()}…` : `${brand} — add a one-line description of what you sell.`),
    who_you_target:
      'B2B decision makers who match your best existing customers — refine the job titles, company size and industries in the next step.',
    how_to_pitch: heading
      ? `Lead with your own headline promise: “${heading.slice(0, 120)}”, then name the specific problem it removes.`
      : 'Lead with the single problem you remove, name it in the buyer’s own words, and ask one question.',
  }
}

export async function analyzeWebsite(url: string): Promise<Generated<WebsiteAnalysis>> {
  const result = await callBackend<WebsiteAnalysis>('/api/onboarding/analyze-website', { url })
  if (result) return { data: result, source: 'claude' }
  return { data: await analyzeOffline(url), source: 'offline', note: OFFLINE_NOTE }
}

/* ================================================ Reply drafting */

export interface ReplyContext {
  conversationId: string
  prospectName: string
  prospectTitle?: string | null
  company?: string | null
  signals: string[]
  intentTag: string
  history: { direction: 'inbound' | 'outbound'; body: string }[]
  bookingUrl?: string | null
}

function draftReplyOffline(ctx: ReplyContext): string {
  const first = ctx.prospectName.split(' ')[0]
  const lastInbound = [...ctx.history].reverse().find((m) => m.direction === 'inbound')?.body ?? ''
  const signal = ctx.signals[0]

  if (ctx.intentTag === 'interested') {
    return [
      `${first} — great, let's do it.`,
      '',
      ctx.bookingUrl
        ? `Here is my calendar so you can pick whatever suits: ${ctx.bookingUrl}`
        : 'Send me two or three windows that work and I will lock one in.',
      '',
      'I will come with the two or three things I would look at first for ' + (ctx.company ?? 'your team') + ', so it is useful either way.',
    ].join('\n')
  }

  if (ctx.intentTag === 'question') {
    return [
      `Good question, ${first}.`,
      '',
      `The short version: most tools tell you a deal closed. We tell you which message got the reply that started it${
        signal ? ` — which matters more when ${signal.toLowerCase()}` : ''
      }.`,
      '',
      'Happiest to show it on your own numbers rather than a demo dataset. Worth 15 minutes?',
    ].join('\n')
  }

  if (ctx.intentTag === 'not_now') {
    return [
      `Completely understood, ${first} — mid-quarter is the wrong time to change anything.`,
      '',
      'I will check back at the start of next quarter. If anything shifts before then, just reply here and I will pick it up.',
    ].join('\n')
  }

  return [
    `Thanks ${first}.`,
    '',
    lastInbound
      ? 'Picking up on your note — the one thing worth checking is whether you can currently see which outbound message produced each reply.'
      : `Following up briefly${signal ? `, mostly because ${signal.toLowerCase()}` : ''}.`,
    '',
    'If that is already solved, tell me and I will stop. If not, worth a short look?',
  ].join('\n')
}

export async function generateReply(ctx: ReplyContext): Promise<Generated<{ text: string }>> {
  const result = await callBackend<{ text: string }>(`/api/inbox/${ctx.conversationId}/generate-reply`, {
    prospect_name: ctx.prospectName,
    prospect_title: ctx.prospectTitle,
    company: ctx.company,
    signals: ctx.signals,
    intent_tag: ctx.intentTag,
    history: ctx.history,
    booking_url: ctx.bookingUrl,
  })
  if (result?.text) return { data: result, source: 'claude' }
  return { data: { text: draftReplyOffline(ctx) }, source: 'offline', note: OFFLINE_NOTE }
}

/* =============================================== Post generation */

export interface PostContext {
  brief: string
  voiceSample?: string | null
  whatYouSell?: string | null
  audience?: string | null
}

function draftPostOffline(ctx: PostContext): string {
  const audience = ctx.audience ?? 'B2B founders'
  const claim = ctx.brief.replace(/\.$/, '')

  return [
    `${claim.charAt(0).toUpperCase()}${claim.slice(1)}.`,
    '',
    `Most ${audience.toLowerCase()} treat this as a copy problem. It is a timing problem.`,
    '',
    'Three things we changed:',
    '',
    '1. Stopped writing clever openers and named the thing the buyer had already said out loud.',
    '2. Only reached out in the two weeks after something actually changed on their side.',
    '3. Answered every interested reply within the hour instead of the next morning.',
    '',
    ctx.whatYouSell
      ? `We build ${ctx.whatYouSell.replace(/^A |^An /i, '').replace(/\.$/, '')} — so we watch this closely.`
      : 'None of it required more volume.',
    '',
    'What would you add?',
  ].join('\n')
}

export async function generatePost(ctx: PostContext): Promise<Generated<{ text: string }>> {
  const result = await callBackend<{ text: string }>('/api/content/generate', {
    brief: ctx.brief,
    voice_sample: ctx.voiceSample,
    what_you_sell: ctx.whatYouSell,
    audience: ctx.audience,
  })
  if (result?.text) return { data: result, source: 'claude' }
  return { data: { text: draftPostOffline(ctx) }, source: 'offline', note: OFFLINE_NOTE }
}

/* ==================================================== Free tools */

export type ToolKind = 'cold_email' | 'linkedin_post' | 'icp' | 'linkedin_message' | 'email_sequence'

function runToolOffline(kind: ToolKind, input: Record<string, string>): string {
  const sell = input.what_you_sell || input.business || 'what you sell'
  const who = input.recipient || input.audience || input.best_customer || 'your buyer'
  const signal = input.signal?.trim()
  const firstName = (input.recipient || '').split(/[\s,]/)[0] || 'there'

  switch (kind) {
    case 'cold_email':
      return [
        `Subject: ${signal ? `${signal.toLowerCase().replace(/\.$/, '')} — quick idea` : 'quick idea for your pipeline'}`,
        '',
        `Hi ${firstName},`,
        '',
        signal
          ? `Noticed ${signal.replace(/\.$/, '')}. That usually means the next few weeks are about keeping the pipeline ahead of the new capacity.`
          : `You are probably being pitched a lot this week, so I will be quick.`,
        '',
        `We do ${sell.toLowerCase().replace(/\.$/, '')}. For teams like ${who.toLowerCase()}, the thing that moves is usually knowing which message produced each reply — not sending more of them.`,
        '',
        'Worth 15 minutes, or is this already solved on your side?',
      ].join('\n')

    case 'linkedin_message':
      return [
        `Hi ${firstName} — ${signal ? `saw ${signal.toLowerCase().replace(/\.$/, '')}. ` : ''}I work on ${sell
          .toLowerCase()
          .replace(/^a /i, '')
          .replace(/\.$/, '')}.`,
        '',
        'Not pitching in a connection note — genuinely curious how you handle it today. Worth connecting?',
        '',
        `(${signal ? 'Signal-led' : 'Cold'} note, ${'Hi ' + firstName}… is 280 characters or fewer so LinkedIn will not truncate it.)`,
      ].join('\n')

    case 'linkedin_post':
      return draftPostOffline({ brief: input.topic ?? 'One thing we changed this quarter', audience: input.audience, voiceSample: input.voice_sample })

    case 'icp':
      return [
        'IDEAL CUSTOMER PROFILE',
        '',
        `Business: ${sell}`,
        '',
        'Job titles: Founder, CEO, VP Sales, Head of Growth, Sales Director',
        'Company size: 10–250 employees',
        'Industries: B2B SaaS, Marketing agencies, Professional services, Fintech',
        'Geographies: United States, United Kingdom, Canada, Germany',
        '',
        'Buying signals to watch:',
        '• Two or more open sales roles in the last 30 days',
        '• A revenue leader who changed roles within 30 days',
        '• Engaged with a competitor’s content',
        '• Viewed your profile or commented on your post',
        '',
        'Disqualifiers: under 10 employees, no existing outbound motion, no named revenue owner.',
      ].join('\n')

    case 'email_sequence':
      return [
        `SEQUENCE — ${sell} → ${who}`,
        `Goal: ${input.goal || 'a 15-minute call'}`,
        '',
        'DAY 0 · Email',
        'Subject: quick idea for {{company}}',
        `Hi {{first_name}} — noticed {{signal}}. We do ${sell.toLowerCase().replace(/\.$/, '')}. The teams we help usually cannot name which message produced each reply. Worth a short look?`,
        '',
        'DAY 2 · Email',
        'Subject: the number I mentioned',
        'One data point: teams that fix reply attribution typically find 20–30% of pipeline came from a message they were about to cut. Happy to show how we get to that number.',
        '',
        'DAY 4 · Email',
        'Subject: re: quick idea',
        'Did this land, {{first_name}}? If the timing is wrong, tell me when to come back and I will.',
        '',
        'DAY 7 · Email',
        'Subject: closing the loop',
        'Last one from me. If this is not a priority at {{company}} this quarter, no problem at all — I will stop here.',
      ].join('\n')

    default:
      return ''
  }
}

export async function runTool(kind: ToolKind, input: Record<string, string>): Promise<Generated<{ text: string }>> {
  const result = await callBackend<{ text: string }>('/api/tools/generate', { kind, input })
  if (result?.text) return { data: result, source: 'claude' }
  return { data: { text: runToolOffline(kind, input) }, source: 'offline', note: OFFLINE_NOTE }
}
